Feature/about html
IhorMelnykov/team-project pull request #3
Opened 2022-09-17 12:41 UTC by yarqui

Не розумію, як зробити правильно в github desktop.
Я працюю над своєю секцією в своїй гілці. За цей час ти щось додав до main. Як мені зробити, аби ці зміни в main пішли в мою гілку? Переходжу в гілку main, там видно, що були останні зміни, але в моїй гілці вони не з'являються. Тому попередньо створюю пулл ріквест. Можливо потім зможу стягнути зміни в свою гілку..

2022-09-17 18:38 UTC, yarqui commented
Вже розібрався з попереднім питанням.
Я тут ще зробив пару коммітів вже із стилізацією мобільної версії.

2022-09-17 18:43 UTC, yarqui commented
Перечитав ТЗ по корові: Декоративне зображення з коровою абсолютно спозиціонувати згідно макету.
Перероблю.

2022-09-18 00:40 UTC, IhorMelnykov requested changes

2022-09-18 00:40 UTC, IhorMelnykov commented on src/sass/layouts/_about.scss
> +  &__image {
як ти і написав вже в своєму коменті - абсолютно спозіціонувати коровку). вже в курсі що виправити). по всьомі іншому наче ок.

2022-09-18 08:08 UTC, yarqui commented on src/sass/layouts/_about.scss
> +  &__image {
спозиціонував. перевір, будь ласка

2022-09-18 13:22 UTC, IhorMelnykov approved these changes

2022-09-18 13:22 UTC, merged